name: release
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: actions/configure-pages@v5
      - run: node --run build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist
  pages:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://raviqqe.com
    steps:
      - uses: actions/deploy-pages@v4
  release:
    needs:
      - build
      - pages
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success -o $result = skipped ]; done
